---
title: "读书:《娱乐至死》"
date: 2020-02-01T09:24:31+08:00
type: post
isCJKLanguage: true
categories:
    - "category1"
tags:
    - "tag1"
    - "tag2"
---

= 读书:《娱乐至死》

今天要和大家分享的书是尼尔·波兹曼的《娱乐至死》。娱乐至死，这个词我们或多或少都有耳闻，虽然这本书出版于1985年，并且讨论的目标主要是电视机娱乐，但直到互联网时代，这个观念才逐渐为人所熟知。用书中的话说，*这本书是对20世纪后半叶美国文化中最重大变化的探究和哀悼，即印刷术时代步入没落，而电视时代蒸蒸日上*。

在《一九八四》中，人们受制于痛苦，而在《美丽新世界》中，人们由于享乐失去了自由。奥威尔担心我们憎恨的东西会毁掉我们，而赫胥黎担心的是，我们将毁于我们热爱的东西。这本书想告诉大家的是，可能成为现实的，是赫胥黎的预言，而不是奥威尔的预言。

本书作者尼尔·波兹曼是世界著名媒体文化研究者和批评家，生前一直在纽约大学任教，首创了媒体生态学专业。

《娱乐至死》全书一共十一章，大体可以分为三部分。

第一部分即第一、二章，着重探讨了**媒介的本质是什么**。第二部分即第三、第四，介绍了印刷术时代的美国及其思想。第三部分从第五章到第十章，介绍了**阐释时代**，即通过印刷术获取知识的时代，的没落和以电视机普及为标志的**娱乐业时代**的兴起，并分别介绍了娱乐业时代，美国的新闻、政治、传教、教育四个领域所发生的变化，限于篇幅，我只会选取新闻和教育做讲述。

首先我们要了解什么是媒介，为什么媒介即隐喻、即认识论。简单来说，媒介就是我们传递信息的工具，比如远古时代的口语、早期的文字、近代的印刷术、电视机，乃至现在的电脑、手机，每个时代都有其主要的信息媒介。但波兹曼认为，媒介又不仅仅是工具，不同的媒介会塑造不同的文化，*媒介本身就会影响人们对于信息的认知*。

**隐喻**是一种通过把某一事物和其他事物作比较来揭示该事物实质的方法。作者认为**交流的媒介对于这个文化的精神重心和物质重心的形成有着决定性的影响， 而且这种介入却往往不为人所注意**。
比如，人类为了度量时间发明了钟表，但钟表作为时间的媒介，反过来將人类从大自然的日出日落中解放了出来。芒福德总结说："`钟表是一种动力机械，其产品是分和秒。`"
在制造分秒的时候，钟表把时间从人类的活动中分离开来，并且使人们相信时间是可以以精确而可计量的单位独立存在的。
分分秒秒的存在不是上帝的意图，也不是大自然的产物，而是人类运用自己创造出来的机械和自己对话的结果。我们需要了解时间，就必须借助钟表，钟表成了时间的隐喻。所以作者说，*媒介即隐喻*。

认识论是一门有关知识的起源和性质的复杂而晦涩的学问。第一章说过，对于真理的认识是同表达方式密切相联的。
西方有谚语说，人们害怕真理，所以她穿上了故事的外衣。故事就成了真理的媒介，寓言、就是这种典型的故事。
作者相信，电视作为一种新的媒介，取代了印刷术，充当我们的新媒介，会改变我们的认识论。

总的来说，作者在前两章里强调了一个观点，即**媒介会影响我们获取知识的最终结果**。
下面，我们来看，美国早期，电视机发明之前，在印刷术统治下的图景。作者分两章，第三章介绍了印刷机时代，美国的文化氛围，
第四章介绍了美国的政治文化和思想。可以明显感受到作者主观上是非常推崇和怀念那个时代的。

首先，作者分析了当时美国文化繁荣的原因。总结起来可以归为以下三点：

. 法律政策的支持推动
. 良好的阅读文化基础
. 英国已有的知识积淀

然后，作者列举了当时美国的诸多实例，以证明那个时代的美国因为文字而文化昌盛、思想深刻。比如1776年出版的《常识》能在两个月内卖掉10万册，报纸的兴起等。

第四章，作者介绍了当时的美国，思想也很活跃和繁荣，具体表现为高质量的文化活动，如政治辩论、树墩演讲、严肃理性的广告。

后面，作者进一步分析了背后的原因，并得出结论：是因为印刷术，美国才得以跻身于世界优秀文明之林。

最后一部分，作者开始讲述印刷制品的没落和以电报、电视机为代表的娱乐业的兴起。

首先，什么叫"`阐释时代`"，即印刷机统治美国人思想的那个时期。那个时代的特征是：富有逻辑的复杂思维，高度的理性和秩序，对于自相矛盾的憎恶，超常的冷静和客观以及等待受众反应的耐心。而到了19世纪，进入了"`娱乐业时代`"，即电报、电视机统治美国人思想的时代。

电报的出现**让信息的传播突破了空间的限制**，电报和报纸结合的新形态开始出现，由此，也让**信息过剩**的问题第一次出现在人类历史上。

除了电报，摄影术也被发明出来，波兹曼认为摄影术是描述特例的、割裂的，破坏了原有的文字符号环境。
对于美国人来说，看取代了读。波兹曼最后说道："`在它即将逝去的旋律下，一个新的音符已经响起，确定曲调的正是摄影术和电报。
在它们的语言中，没有关联，没有语境，没有历史，没有任何意义，它们拥有的是用趣味代替复杂而连贯的思想。
它们的语言是图像和瞬息时刻的二重奏，一起吹响了迎接美国公众话语新时代的乐章。`"

波兹曼认为，我们进入了一个**躲猫猫的时代**，其特征是，信息支离破碎，就像电视上的新闻片段一样，一会进入你的视线，又很快消失。

伴随着阐释时代的没落，娱乐业时代兴起，但娱乐业时代并不是阐释时代的延续，以电视机为代表的媒介　使得思考无法得到很好的表现，电视需要的是表演艺术。

"`好......现在`"常被用于广播和电视的新闻节目，目的在于指出我们刚刚看到或听到的东西毫无关系。电视上的新闻表现为独立和割裂的特征，经常由一个又一个彼此独立的片段组成，并尽量避免观众的思考和共鸣。

电视节目也开始占据学校的角色，让娱乐成为教育的一部分。但基于电视的教育却显得肤浅，缺乏推理和思考。
西赛罗说过，教育的目的是让学生们摆脱现实的奴役，而现在的年轻人正竭力作着相反的努力－－为了适应现实而努力改变自己。

最后，作者发出来赫胥黎的警告，即"`*人们感到痛苦的不是他们用笑声代替了思考，而是他们不知道自己为什么笑以及为什么不再思考*`"。

作者也指出：*只有深刻而持久地意识到信息的结构和效应，消除对媒介的神秘感，我们才有可能对电视，或电脑，或任何其他媒介获得某种程度的控制*。

结尾，谈几点我的感悟：

* *娱乐是思想的尼古丁*：统治者用以维稳、被奴役者获得快乐。参考香港的娱乐业和经济特征。
* *获取真理的过程一直都是艰难晦涩、曲折繁复的*，不要妄图会有那种媒介会把赤裸裸的真理呈现给你：从报纸到电视到电脑乃至手机，一直如此。
* 无论是以前的电视，还是现在的短视频，*内容生产者总是希望用最容易接受的方式抢夺用户的注意力，但这些方式只会让用户娱乐至死*。
* 每个守旧者被时代的车轮碾过时，多少都会振臂高呼，但终究无济于事。大多数人终究是乌合之众。*无论当前的媒介是什么，都终究只是既得利益者奴役民众的工具*。
* 最后，*只有深刻的认识媒介，才能称为媒介的主人*。以互联网为例，对于有些人而言，它是沉迷其中的毒药，对于有些人而言，它却完成了稀缺资源对长尾用户的再分配。
