---
title: "成为一个完整的社会人"
date: 2020-02-06T20:11:55+08:00
type: post
isCJKLanguage: true
categories:
    - "随笔杂记"
---

= 成为一个完整的社会人

== 引言

本文是笔者的一些自我反思，工作一年半以来，不足之处的复盘。整理成文，以告过往，以警将来，希望对别人亦有所帮助。

本文将一个完整的社会人应该具备的能力分成了两大类：必修和选修。和大学里面的课程类似，必修是那些我认为必须习得的能力，缺乏了就会**影响自己的基础生存状态，可能过不好这一生**，而选修是个人主观选择的，*缺乏不会有严重影响，但习得会有诸多益处*。

当然，本文只是我自己的一些碎碎念，仅供参考，还请指正。

== 必修

=== 专业技能

专业技能基本就是我们的工作了，作为毕业没多久的人，我能感觉到的是很多人羡慕程序员高薪，程序员又羡慕算法研究员高薪，并担心自己的中年危机。总之，每个人、每个职业都有自己的围城，但我觉得，即使再不满意，也要打造好自己的专业技能，尤其是在大学期间，只有基本盘稳了，才有精力去追求更长远的目标。

=== 工作能力

专业技能是工作能力的核心，但不是唯一要素，工作能力是一个复杂的有机体，比如沟通能力、团队协作能力、职场思维、为人处世等等，即使单独出来，也是一个非常庞大的体系，在此不做赘述。

=== 生活常识

* 衣食住行的常识
 ** 正常的穿搭审美
 ** 识别地沟油
 ** 防止租房被坑
 ** 等等
* 基本的法律知识
* 检索信息的能力
* 基本的沟通技巧
* 等等

生活常识是非常宽泛的，从一片牛肉涮多久能熟到什么样的红灯可以右转，很多时候，常识是我们被动需要的（比如工作几年需要买车买房），当有机会学习时，一定不要排斥。

=== 卫生健康

比如最近的疫情，就是一起典型的公共卫生事件。再比如，自己19年曾经出现过一次急性肠胃炎，后来反思主要原因是周五吃海底捞喝了酒，还可能吃了没熟透的东西，周末又有点着凉，所以，一定要保护好自己身体。

此外，还有一种就是慢性的伤害，比如久坐、肥胖、办公室颈椎病等。建议

* 每年体检
* 坚持锻炼，有氧无氧结合
* 病从口入，注意饮食
* 规律的作息时间

=== 人际关系

和家里人经常联系，哪怕没什么事情也要报个平安。和朋友既要把握尺度，也不要过于拘谨。和恋人要注意男女思维差异，好好磨合，做好长期规划。

== 选修

=== 终身学习

这其实是一个非常抽象的话题，我举两个例子，今年由于疫情，乡镇上的车很少，恰巧我爸买了车，自己拿了驾照以来也没正式开过车，于是我就借此机会从纸上谈兵变成了"`秋名山车神`"。第二个例子是我妈为了减肥买了个呼啦圈，我也拿起来试了下，结果立马掉了下来，我开始思考，似乎每次腰的方向要和呼啦圈反着才能转起来，于是失败了几次终于成功了。

生活中，既有像开车这样客观需要的能力，也有像转呼啦圈这种技多不压身的能力，所以，我把终身学习放在了第一位，如乔布斯所说：*Stay hungry,Stay foolish*。

比较尴尬的是我至今还没学会带隐形眼镜～

=== 理财能力

其实自己做的挺差的，一方面理财教育是大学教育缺失的，另一方面，可能很多人像我一样工作之前并没有多少闲钱去锻炼理财意识，所以导致工作后的存钱方式就是储蓄。

只要花半天时间，一个普通人就能理解储蓄是跑不赢通货膨胀的。当然，关于理财，我也只是入门小白，没什么多说的。

=== 自我管理

主要包括

* 精力管理：工作、生活、学习、娱乐等的平衡
* 时间管理：高效工作、高效学习
* 欲望管理：控制游戏、短视频这种只能获得短期快感的娱乐投入
* 信息管理：每天看到的有价值的信息如何管理

其他的欢迎补充

=== 娱乐能力

比如有的人喜欢做菜、有的人喜欢打游戏、有的人喜欢打球，生活总有一些空余时间，如果没有一二兴趣爱好，是很难过得充实的，我觉得打游戏也好、运动也好，只要不本末倒置，只要能让自己身心有所愉悦，适度投入都是值得的。

=== 阅读能力

我是非常推荐读书的，当然看优质文章、帖子也可以。之前腾讯内部就有个投票，讨论信息是否有必要通过看书获取，我记得大部分人觉得没必要，因为有很多其他渠道，也确实符合大势。但

我相信，*阅读能力是独立于媒介的，如果没有阅读能力，就只能获得信息，而不能获得知识*。

=== 结构化思维

大多数时候，我们都在做三件事：

* 获取信息：公众号、论坛、微博等等
* 处理信息：思考
* 表达结论：发朋友圈、发帖等等

其实这是一个非常复杂的过程，比如：

* 信息是主动获取的还是被动接受的，有没有经过检验查证
* 思考是盲目接受还是主动去推理的，是否有技巧，如金字塔思维、辩证法、换位思考等
* 表达通过口语还是文字，是否表达准确、完备等。

比如，我这篇文章，信息是否足够全面，分类是否足够合理，表达是否足够通畅，这就是结构化思维的习得锻炼。

这个其实也是一个非常庞大的分支，自己也在努力学习。

=== 平稳心态

最后，可能我们听过很多道理，学了很多技能，也过不好这一生，会和恋人吵嘴、会被工作打击，会羡慕别人的家底或时运。等我们走出了象牙塔，才发现这个社会可能比我们想象的还要不公平、还要黑暗。不如意事十八九，可语言人无二三。

所以，我觉得最后一个能力叫**平稳心态**。有人觉得我佛系，有人觉得我上进，我自己而言，我更信奉一个道理：*以老庄之心，立孔孟之业*。所谓，尽人事，听天命。

以上。

== 参考

* https://www.zhihu.com/question/21170885[毕业生必备的技能有哪些？]
* https://www.zhihu.com/question/35112627[有哪些必备的知识技能？]
* https://www.zhihu.com/question/303482683[人在年轻的时候，最核心的能力是什么？]
