---
title: "拾屋记"
date: 2020-06-21T20:16:53+08:00
type: post
isCJKLanguage: true
categories:
    - "category1"
tags:
    - "tag1"
    - "tag2"
---

= 拾屋记

最近要搬家，周末收拾了下，记录一点感悟。

== 破窗效应

本来整洁有序的房间，因为一两次松懈，或是没有及时把用过的物品归回原位，或是没有及时清理产生的垃圾，就形成了一扇破窗。破窗的产生导致了自己对周围环境要求的降低，进而形成恶性循环，开始纵容越来越多破窗的产生。

== 修复成本

整理的时候，发现一个音乐盒布满了灰尘，但是又不能直接扔了，由于音乐盒零件精细，清理起来十分费劲。就像代码中那些**不可抛弃又不经常使用**的模块一样，如果久不维护，那么就会"`布满灰尘`"，如果再加上人员变动、需求更迭，就会在某一天需要时产生巨大的修复成本。

== 伪需求

整理的时候发现两个最近几乎从来没用过的东西：清洗机和泡沫轴。

清洗机是刚来的时候，眼镜经常弄脏，但是直接擦拭又很伤眼镜，加之耳钉也需要经常清洗，于是就买了一个。后来发现每天早晨去公司用水龙头冲洗眼镜既方便又干净，加之后来都是用耳扣而不是耳钉，清洗机就没怎么用过了。

泡沫轴买了之后不久，又有了一个筋膜枪，比泡沫轴方便了很多，所以也没怎么用了。

这两个算是伪需求了，买的时候没想清楚。清洗机已经有其他等效的替代方案了：水龙头。而泡沫轴存在一个更优的解：筋膜枪。所以以后买东西还是不要轻举妄动，弄清楚自己需求的本质是什么，很重要。

最后还有一个单反，大学时买的，但也没怎么用过，就一直带着，相机包直接发霉了（深圳太潮湿了～）。但这个也不能算伪需求吧，只是当时的明月光已经成了现在的饭黏子，如果当时不买，终究还是意难平，也罢也罢。

== 过度设计

还有一个台灯也是从来没用过，刚开始布置电脑桌的时候，电脑是直接放在桌子的，屏幕向上，于是就会反光，遂想着放个台灯。结果后来买了个电脑支架，屏幕和头一样高，还要稍稍向下一点，亦便不会有反光的问题了，台灯也就成了摆设。

感觉这个问题有点过度设计了，用了一个成本很高、很笨重的方法去解决一个很小的问题。有时候真是当事时迷，复盘时清～

== 职责划分

整理的时候发现蜂窝护膝丢了一只，可能是放在哪个角落了，也可能就是打球时忘了带回来了，也不记得了。每次要去打球，要么是忘了带擦汗毛巾，要么是忘了带运动眼镜，昨天想了想，这些东西应该都放在一个收纳盒的。

如果不划分职责，按照功能分模块，调用的时候真的不知道怎么查找。

以上，碎碎念。
