---
title: "读书:《乡土中国》"
date: 2019-12-22T09:18:06+08:00
type: post
isCJKLanguage: true
categories:
    - "读书笔记"
---

= 读书:《乡土中国》

== 概览

本书是费孝通1937年在云南教书时，从《乡村社会学》这门课的讲义中整理而来，书中的观点都是作者实地考察和教学思考的结果，充分分析了乡村社会的特点及其成因，豆瓣评分9.2，当之无愧的大师之作。不同于柏杨在《丑陋的中国人》中一味的批评与鄙视，费老不仅客观地描述了现象，并结合自己的知识做了成因的分析，很有启发性。

== 乡土本色

"`从基层上看去，中国社会是乡土性的`"。"`土`"指泥土、土地，农耕文化养育了中国的礼俗文化，人与人之间靠的是熟悉、信任；殖民文化养育了法理社会，人与人之间靠的是契约精神。

== 文字下乡

首先要明确文字和语言在人与人之间交流时所起的作用，文字和语言在乡土社会作用被减弱（声音、动作、表情的交流更加准确、生动）。乡土社会缺乏文字普及，并不是因为乡村"`不文明`"，而是因为"`非文字`"的交流途径是乡村生活自然演进的结果。乡土社会是个面对面的社会。

== 再论文字下乡

个人的今夕之隔，社会的世代之隔。文字克服了个人记忆和社会传承在时间长河中的局限性，但乡土文化的总量相对有限，传承靠口口相传（记忆）足以完成。

== 差序格局

差序格局：以个人为中心，以生育和婚姻关系为纽带，形成的错综复杂的人际关系网络。区别于西方社会的团体格局。

== 系维着私人的道德

不同的社会组织形式产生不同的道德体系，差序格局要求"`克己复礼`"，以个人为中心发散出不同的关系线：亲情线（孝悌）、友情线（忠信）...​

== 家族

乡土社会的家庭是沿父系单系传递的，在结构上是一个氏族，称为家族。家族必须是绵续性的，因为政治、经济、宗教等事务是长期绵续性的，所以家族不因个人的成长或死亡而分裂或结束。

== 男女有别

感情定向：文化所规定个人感情可以发展的方向。亚普罗和浮士德两种两性感情观的冲突。乡土社会是一个孤立的小天地，不需要新的社会关系，以同性为主轴、异性为辅轴的单系组合更适合于完成社会事业的需要。将天国现世化，以现世为天国。对生活的态度是以"`克己`"来迁就外界，一切足以破坏秩序的要素都被遏制，男女的鸿沟由此筑下。

== 礼治秩序

人治VS法制。礼VS法。乡土社会中，传统的权威性使人产生敬畏感，人们出于内心的服膺以传统来规范自己的行为，来规范人与人之间的关系。所以，乡土社会是礼治社会。

== 无讼

乡土社会，解决纠纷的主要目的乃是完成教化（礼）。法律不是为了教化，而是为了保护个人利益。法治抑或礼治，取决于社会变迁程度。社会变迁加剧，人口流动的冲击下人们相互不再熟悉，人们的合作只能以契约来维持。

== 无为政治

政治权力分为两种，完全靠暴力维持的横暴权力和根据契约而产生的同意权力。横暴权力存在的基础是经济利益的诱惑，同意权力存在的基础是社会分工合作。乡土生活的主流是自治，即礼治社会的自发运行。

== 长老统治

乡土社会中的权力，既非专制的亦非民主的，而是教化性的。乡土社会在长幼之序的规范下自然产生宗族长老，宗族长老行使教化性的权力来维护乡土的稳定。

== 血缘和地缘

在乡土社会中的地缘关系依附于血缘关系，地缘是血缘的投影。血缘社会中商业很难发展。地缘是从商业里独立壮大的社会关系，人情问题不再成为商业发展的限制。

== 名实的分离

乡土社会中的长老权力是稳固的，但为了应对社会缓慢变迁的需求而产生了名与实分离的现象。即承认或说维持形式上的长老权力意志，而在内容上加以注释和曲解，从而实现改变。名与实的分离，就是乡土社会的变迁。

== 从欲望到需要

从"`欲望`"到"`需要`"，就是从自发到自觉。乡土社会是自发的，缓慢变迁的，也是稳定的；现代社会是自觉的，快速变迁的，也是不稳定的。

== 读后感

农村90后：最动荡的一代

每逢过年，总能看到很多关于家庭矛盾的帖子，我们这一代或许是家庭矛盾最多的一代，而过年，则是接受了现代教育的我们和乡土文化最直接的交锋。按照费老在《乡土中国》中的解释，长久以来，以泥土为底色的农耕文化一直是中国乡村的基石，基于此，农村最大的特点就是稳定、空间隔离、家族关系、长幼尊卑。改革开放几十年来，越来越多的人外出务工，传统的乡村体系的稳定性遭到破坏，以这种观念稳定性为基础的一系列文化自然也受到了挑战。我们的父辈在乡村社会长大、在现代社会生存，他们或多或少还保留这在乡村社会中生存的能力，比如处理错综的亲属关系，逢年过节的礼数等等。而我们这一代，则是彻底成长在现代社会的一代。

知乎上有个问题："`你为什么不愿意回家过年了？`"，一个高赞回答如是说："`我改变不了那个世界，却又不愿屈从于那个世界`"。但对于农村的90后来说，这是不得不面对的。我们的观念和父辈是有冲突的，而且父辈的观念在农村这个特定时空里或许是更加适用的。回归到传统是不可能的，对于农村90后来说，他们不可能像城里孩子那样，处在一个合适的土壤里，摆在我们面前的是如何处理好这种冲突，以及如何早日脱离这个时空，完成从思想到生活彻底的现代化。

== 参考链接

* 乡土中国
+
____
(豆瓣)
____

* 读《乡土中国》（乡土中国）书评
