---
title: "读书:《吃掉那只青蛙》"
date: 2020-06-20T09:44:18+08:00
type: post
isCJKLanguage: true
categories:
    - "category1"
tags:
    - "tag1"
    - "tag2"
---

= 读书:《吃掉那只青蛙》

== 笔记

=== C01 明确目标

* 第一步：明确你究竟想要什么
* 第二步：把你的目标写下来
* 第三步：为你的目标设定一个完成的最后期限
* 第四步：为了实现目标，把你所能想到的、所有要完成的事项都列在一个清单上
* 第五步：进一步梳理整个清单，使之成为一份计划
* 第六步：根据计划马上采取行动
* 第七步：每天解决一部分问题，向前推进主要目标的实现

=== C02 制定计划

* 制定计划可以提高工作效率、节省出更多的时间
* 如果你一直坚持先列出清单再开始工作，那么，从一开始你的生产力就能提高25%，相当于每天节省出两小时
* 针对不同的目标，制定不同的计划
* 总计划、月计划、周计划
* 为将要完成的项目制定计划

=== C03 将80/20法则用于你的所有任务

关注重要活动，不要被小事所引诱

=== C04 考虑效果

* 一旦确立了清晰的长期目标，你就能参考目标评估目前的活动，并确保该活动符合你的最终目标。
* 成功人士是那些懂得延迟满足感，愿意做出短期牺牲来追求长期高回报的人。与这些成功人士不同的是，平庸者是更多地考虑短暂的快乐并容易满足的人，他们几乎不站在长期角度上思考未来。
* 时间有限，任何人都无法做完所有的事情。但只做那些以后能获得正面效果的工作，做与完成最大目标有关的工作，你的时间是足够的

问自己3个问题

. 我的最高价值的工作是什么？
. 我只有把哪件事情做好了才会产生非凡的影响？
. 在此时此刻，对我来说最有价值的事情是什么？`"

=== C05 学会说不

你的任务就是，对那些优先级低的任务进行拖延，从而可以腾出更多的时间来做那些改变你的工作和生活的任务。

=== C06 持续不断地练习使用ABCDE法

=== C07 聚焦关键结果领域

* 每一项工作一般都可以分解为5～7个关键结果领域（key result area，KRA），超过这个数字的很少。
* 明确关键结果
* 明确自己定位

=== C08 遵守3个定律

* 每天只做一项工作
* 马上行动起来
* 快速列出清单
* 时间管理是实现目标的方法
* 工作时间要全身心地工作

=== C09 做好充分准备在行动

* 创造舒适的工作空间
* 只要大方向正确就行就行，然后边干边调整

=== C10 每次到达下一个油桶

=== C11 升级核心技能

在自己的关键任务上能够做到精益求精

=== C12 找到最关键的限制因素

* 找出限制因素
* 运用二八法则
* 从自身找原因

=== C13 自我设定压力目标

* 成为业内领军者
* 为自己设定最后期限

=== C14 激励自己将理想转化成行动

* 建立积极的态度
* 乐观者的4个特征：
* 任何情况下都会去看好的一面
* 总能从挫折苦难中总结经验
* 总是极力找出解决办法
* 不断思考和谈论自己目标

=== C15 技术是一个可怕的掌控者

* 要有所选择
* 一定不能上瘾
* 找回属于自己的时间
* 不要成为高科技的奴隶

=== C16 技术是一名出色的仆人

* 掌握你的通信
* 遇到突发事件

=== C17 高度的专注力

* 上瘾：多巴胺
* 多任务引发的幻觉
* 提高生产力：1-每天提前制定一整天的计划，优先完成最重要的任务；2-持续工作90分钟，再休息15分钟；

=== C18 奶酪和香肠工作法

* 设定强制关闭机制
* 任务需要分解

=== C19 创造整块的时间

* 为整块时间制定时间表
* 使用时间计划表
* 也要利用好碎片时间

=== C20 保持紧迫感

* 进入最佳状态：心流
* 通过内在紧迫感建立行动偏好，立刻采取行动
* 激发动能，惯性的良性循环
* 马上行动

=== C21 单独处理每一项任务

* 一旦开始，全力以赴
* 不浪费时间，自律是关键。

== 总结

讲了这么几个问题：

. 磨刀不误砍柴工：目标和计划很重要
. 要把时间和精力投入最重要、受益最高的事情
. 做好准备，立即行动，分割目标，最终实现大目标
. 找出效率瓶颈，突破限制因素，升级核心技能
. 给自己设定目标和压力，做一个自律、自驱的人
. 和技术和谐相处，善用而不溺用
. 创造整块时间、善用碎片时间，把任务拆分开，因为人总是急于完成
. 单独处理，不要多线程切换

== 摘录

青蛙，代表的是那些极具挑战性，做了就能带来很大价值的事情。

你永远不可能完成所有事情，也永远无法完成你要做的所有任务

你只有改变自己的思维方式、工作方式以及处世的方式，才能自如地驾驭你的时间，掌控自己的生活。你只有学会放弃，把时间和精力放在那些能够改变你生活的重要事情上，才能有效地安排你所要面对的那些事情。

你不能教会一个人所有的事情，你只能引导他从自身出发，去解决问题

如果你每天早上醒来做的第一件事情是吃掉一只活的青蛙，你就会欣喜地发现，在这一天接下来的时间里，将没有什么比这个更糟糕的事情了

一个人成就的大小取决于他做事情的习惯。分清轻重缓急、克服拖延、先处理最重要的事情，是一种身心相互协调的技能。

在你开始攀登成功的阶梯之前，首先要确定你的梯子没有搭错地方

____
只要我们能善用时间，就永远不用愁时间不够用。 ----歌德（Johann Wolfgang Von Goethe）
____

你要记住，不管你选择先完成什么任务，久而久之都会形成一种固化的习惯。如果你选择每天先做低价值的任务，你将很快养成先做低价值任务的习惯。

事实上，完成一项重要的工作所需要的时间与完成一项不重要的工作所需的时间通常是一样的。区别是你完成重要的、有意义的工作能获得极大的自豪感和满足感。

时间管理实际上也是生活管理、自我管理。事实上时间管理是在控制事件发生的顺序（sequence of events）。时间管理就是控制你接下来应该做什么。

能够卓有成效地工作和具有辉煌成就的人总是磨炼自己，先开始做摆在他们面前最重要的工作。

对于可以改变你的人生和事业的少数活动，你应该花费越来越多的时间

____
伟人之所以伟大，成功者之所以成功，是因为他们把全部的力量集中在一点上。 ----奥里森·斯韦特·马登
____

用长期时间观念的思维优化你做出的短期决定

未来的意义常常会左右目前的行动。

沃伦·巴菲特（Warren Buffett）是全世界最富有的人之一，曾经在分享他成功的秘密时这样说道："`成功的秘密非常简单，我会对当下不重要的事情直接说不。`"

学习时间管理技巧的一个主要目的是，从现在开始，你可以去做那些真正重要的工作，并腾出更多的时间去做那些生活中能给你带来最大的幸福感和满足感的事情。

如果你想保持生活的平衡，工作的时候就要全身心投入。进入公司以后，就抓紧时间，全身心地投入工作。

克服拖延、提高工作效率最好的方法之一，就是在开始工作之前做好充分准备。

我个人的做事原则是"`只要大方向正确就行，然后边干边调整`"，反正车到山前必有路。

只有约2%的人能在完全没有监督的情况下工作，这样的人可以说寥若晨星。

幽默大师艾德·福尔曼（Ed Foreman）曾经说过："`永远不要把你的困难告诉别人，因为80%的人对你的困难不感兴趣，而另外的20%的人也许会对你的遭遇感到幸灾乐祸。`"

每天都会关闭科技设备一段时间，坚持做有规律的锻炼；并且抽出一定的时间冥想，保持自我的内在中心。

曾有一项研究结果显示，人们平均每46分钟会查看一下自己的智能手机。 [2] 另一项研究表明，人们平均每天会查看85次手机，该研究显示："`人们查看手机的频率是他们以为的2倍。`"

____
技术仅仅是工具而已。 ----梅琳达·盖茨（Melinda Gates）
____

"`数字化待办事项清单`"是控制时间的有力工具，它原来的名字是"`任务管理软件`"。它不仅具有纸质待办事项清单的一些优点，还具备一些其他的优势。

____
习惯在养成之初就像一根看不见的细线，但是我们每重复一次习惯，这根线就会变得更粗壮一点，最终它会变成一条粗大的缆绳，把我们的思想和行为牢牢地拴在上面。 ----奥里森·斯韦特·马登
____

"`强制关闭的冲动`"。它的意思是，你开始处理一项任务，并最终完成它，你会感觉更愉快，更加充满力量。你会觉得完成一项任务和项目是潜意识里的一种需要，你必须满足这种需要。就是这种感觉驱使你去完成一项又一项任务和项目，直至彻底完成任务。

我有好几个畅销书作家朋友，他们在动笔写一本书之前，只是下决心每天写一页，甚至只写一段，直到最后写完一本书。你也可以这样做。

高效能、高生产力的诀窍之一是：让你的每一分钟都发挥价值。要充分利用被称为"`时间的礼物`"的旅行和中转时间。你可以利用这些时间来处理一些庞大任务中的一小部分。
