---
title: "读书:《小岛经济学》"
date: 2020-02-16T09:27:34+08:00
type: post
isCJKLanguage: true
categories:
    - "category1"
tags:
    - "tag1"
    - "tag2"
---

= 读书:《小岛经济学》

____
如果将这本书仅仅看作经济学的入门读物，我觉得有失公允，因为这本书对于当下的很多经济现象做了深刻的剖析，且非常鲜明的表达了自己的观点。 + From:推荐序
____

== 概览

一开始以为这本书是入门读物，读完有三点感受：

. 前面还算入门，第九章之后（政府职能转变）就有点复杂了，但是也合情合理。*如果知识本身是复杂的，那就不存在所谓的捷径*。
. 讲的也不是主流的凯恩斯经济学，而是奥地利学派的观点，所以读起来有点**反常识**，权当是开阔眼界了。
. 书中很多隐喻，虽然方便理解，但是也要看到本质，比如"`鱼本位`"的破灭其实是"`金本位`"的破解，即布雷顿森林体系的瓦解。

____
凯恩斯主义: 起源于20世纪30年代经济大萧条时期。他们的主张是，国家应干预和调节经济并使经济平衡发展，也就是传说中的那只看不见的手。 + 奥地利经济学派：起源于19世纪70年代。主张自由经济，即政府不应该插手经济发展。 +
____

另外这本书的英文名字叫__How an Economy Grows and Why It Crashes__，有助于理解本书的主旨。

这本书的特点是把人类的经济发展（主要是美国和近代中国）浓缩到了一个小岛的空间，所以读起来比较聚焦，把发展的脉络呈现得很清晰。所以先给出目录，然后是自己梳理的路线。

----
推荐序／ XI
珍藏版序言／ XV
序 言／ XXI
写在前面／ XXXV
第一章 一个好点子出炉了／ 001
第二章 把财富分享给别人／ 015
第三章 信用卡的多种用途／ 033
第四章 经济到底是如何发展的／ 045
第五章 在鱼被指定为货币之后／ 057
第六章 为什么会有储蓄／ 079
第七章 基础设施与贸易／ 095
第八章 一个共和国就这样诞生了／ 111
第九章 政府的职能开始转变了／ 121
第十章 不断缩水的鱼就像货币一样／ 141
第十一章 中岛帝国：远方的生命线／ 153
第十二章 服务业是如何崛起的／ 167
第十三章 “鱼本位”的破灭／ 179
第十四章 棚屋价格是如何涨上去的／ 191
第十五章 快了！快了！棚屋市场要崩溃了／ 209
第十六章 情形怎么变得如此糟糕／ 227
第十七章 缓兵之计／ 241
第十八章 占领华孚街／ 255
第十九章 无鱼不起浪／ 273
后 记／ 293
致 谢／ 299
----

对应的发展路线：

. 原始社会：生产=消费
. 工具出现：生产力过剩，产生储蓄
. 储蓄的使用方式：存储、消费、投资、借贷
. 储蓄创造了资本，而资本使扩大生产成为了可能，从而产生经济
. 经济促进了货币的产生
. 经济使分工更加明确，基础设施建设和贸易开始繁荣
. 国家开始出现，负责保护公民，代价是收税
. 政府出现，并开始干预经济
. 政府喜欢透支储蓄，导致货币贬值
. 跨国贸易的出现，导致外来生产力的流入，缓解了国内生产力不足
. 由于国家鼓励消费，制造业外迁，服务业崛起
. 由于货币实际已经超过了生产总量，所以这政府将货币和生产脱钩
. 政府将资本注入房地产市场，刺激消费
. 预言了"`美索尼亚国`"经济的大崩溃

== 总结

书中让我印象深刻的一些观点：

* 如何提高生活水平：延迟消费，敢于冒险
* 政府（和背后看不见的手）总是在引导刺激民众超前消费（各种低利率的贷款），因为凯恩斯学派相信：消费促进经济发展。但是，奥地利学派认为经济发展带动民众消费。
* 通货膨胀的结果是物价上涨，本质是政府印发的货币超过了市场实际的生产总值。
* 美元的**储备货币**地位很大程度上导致了美国贸易逆差的增大，如果没有全球经济系统对美元的内在需求，任何国家都无法长期维持这种失衡。
* 奥地利经济学派的三个重要观点：第一，促进经济增长的根本原因是生产，而不是消费；第二，改善恶化的经济状况，需要储蓄，而不是消费；第三，经济不景气时，需要通货紧缩，而不是通货膨胀。

== 参考

* https://book.douban.com/subject/26985299/[小岛经济学 (豆瓣)]
* https://toddtail.xyz/2018/10/30/%E5%B0%8F%E5%B2%9B%E7%BB%8F%E6%B5%8E%E5%AD%A6%20-%20%E7%94%B1%E6%B5%85%E5%88%B0%E5%A4%8D%E6%9D%82%E7%8E%B0%E5%AE%9E%EF%BC%8C%E7%AB%99%E5%9C%A8%E7%BE%8E%E5%9B%BD%E8%A7%86%E8%A7%92%E7%9A%84%E7%BB%8F%E6%B5%8E%E5%AD%A6%E5%90%AF%E8%92%99%E8%AF%BB%E6%9C%AC/[小岛经济学 - 由浅到复杂现实，站在美国视角的经济学启蒙读本 · ToddTail]
* https://kaopubear.top/post/2018-06-06-readingnotexdjix/[思考问题的熊]
* https://www.wodeabc.com/Article/Show/8002032[《小岛经济学》简单书评----我的ABC]
* {blank}
+
[cols=3*]
|===
| [《小岛经济学》
| 读后感
| 读书笔记](http://reading.geek-docs.com/economic/the-island-of-economics.html)
|===

'''

读的也不算很深入，勉强算入门了。

以上
