---
title: "读书:《学会写作》"
date: 2020-01-16T09:21:10+08:00
type: post
isCJKLanguage: true
categories:
    - "读书笔记"
---

= 读书:《学会写作》

最近利用两个周末的时间读完了一本书，叫《学会写作》，豆瓣信息如下：

____
作者: 粥左罗 + 出版社: 人民邮电出版社 + 出品方: 智元微库 OPEN MIND + 副标题: 自我进阶的高效方法 + 出版年: 2019-5 + 页数: 280 + 定价: 59元 + 装帧: 平装 + ISBN: 9787115510556 +
____

读完觉得写的还挺好，尤其是整体架构十分有条理，符合我这种理工男的审美，完整的讲了公众号写作的体系。但是一看评分，只有 *6.8* 分，妥妥的平庸之作，带着好奇，我看了下评论区，其中有一句话给了启发：

____
书名改叫《学会写公众号》可以给满分...然而功利不是写作的全部
____

确实，从公众号写作的角度来说，这本书是接近满分的，作者本人就是成功的公众号运营者，也对身边的成功案例做了大量调研，而且这本书写的十分有条理。一般看完一本书我都会整理一个脑图，但这本书看起来是不需要的，比如第五章的目录如下：

----
第五章 素材能力：性价比最高的能力
    第 1 节 写作素材的八个搜索渠道
    第 2 节 优质素材的六个搜索技巧
    第 3 节 日常积累素材的三个方法
----

每一小节有几个小点都列举的清清楚楚了，所以也没有整理成脑图的必要了。当然网上也不乏批判之声，大概集中在以下几点：

* 作者赶上了风口，自身的积淀支撑不了长期高质量的输出，最终内容都是一色的水文，贩卖焦虑和奋斗
* 很会总结，但逆推成立的并不代表正向进行也是一样的
* 立意不高，停留在"`术`"的层面，并且不是什么大术
* 有包装成分，最终还是披着成功学的外衣收割韭菜，譬如点击量这种东西，业内人才知道有多少水分

个人也是比较认同的，辩证来看，这本书确实有过度包装、局限于公众号写作的一些技巧（但书名又很宏大）、把写作这件事情描述的过于机械化等问题，但是另一面来看，这本书里面的内容确实也有其价值，而且社会需要的也不仅仅是 "`落霞与孤鹜齐飞，秋水共长天一色`" 这种浪漫主义，也需要 "`三大注意八项纪律`" 这种理性冰冷的文字。

最后，我觉得最重要的一点是，自身的积淀要支撑得起写作这门奢侈的爱好。《尚书·虞书·舜典》云：

____
诗言志
____

对于一些人，文字就是工作，就要迎合读者的口味，哪怕真理是残酷的；对于另一些人，文字只是他和世界交流的一个窗口。

参考

* https://book.douban.com/subject/33452654/[学会写作 (豆瓣)]
* https://www.zhihu.com/question/61405815[如何看待粥左罗的成功经历？ - 知乎]
