---
title: "毛选精读（一）内核：《实践论》与《矛盾论》"
date: 2020-10-17T23:44:11+08:00
type: post
isCJKLanguage: true
categories:
    - "category1"
tags:
    - "tag1"
    - "tag2"
---

= 毛选精读（一）内核：《实践论》与《矛盾论》

== 概述

个人认为，读毛选应该先读《实践论》和《矛盾论》，这两篇发表于1937年下旬的文章，上承土地革命战争（1927～1937），下启启抗日战争和解放战争。在过往的十年里，共产党先后经历了右倾机会主义和左倾冒进主义的错误，造成了惨重的革命损失，最终在遵义会议确定正确的领导核心。
领袖的这两篇文章，是对过往错误思想的一次彻底批判和总结，也对今后全党全军走上正确的革命道路产生了重要作用。同时，这两篇文章可以认为是毛选的基调和内核，每篇文章，都可以看作是马克思主义唯物辩证法结合中国具体国情的应用。

== 《实践论》

《实践论》产生的背景是：

____
在中国共产党内，曾经有一部分教条主义的同志长期拒绝中国革命的经验，否认"`马克思主义不是教条而是行动的指南`"这个真理，而只生吞活剥马克思主义书籍中的只言片语，去吓唬人们。还有另一部分经验主义的同志长期拘守于自身的片断经验，不了解理论对于革命实践的重要性，看不见革命的全局，虽然也是辛苦地----但却是盲目地在工作。这两类同志的错误思想，特别是教条主义思想，曾经在一九三一年至一九三四年使得中国革命受了极大的损失，而教条主义者却是披着马克思主义的外衣迷惑了广大的同志。毛泽东的《实践论》，是为着用马克思主义的认识论观点去揭露党内的教条主义和经验主义----特别是教条主义这些主观主义的错误而写的。因为重点是揭露看轻实践的教条主义这种主观主义，故题为《实践论》。毛泽东曾以这篇论文的观点在延安的抗日军事政治大学作过讲演。
____

《实践论》讨论的核心问题是：如何通过正确的认知（阶段一），发挥主观能动性改造自己、改造世界，并在这种实践中检验认知（阶段二），进而修正认知（阶段三）。这个过程可以分为3个阶段。

=== 感性认知到理性认知

理性认知依赖于感性认知，认知的感性阶段有待于发展到理性阶段。

那么为什么要深化感性认知：

____
感性的认识是属于事物之片面的、现象的、外部联系的东西，论理的认识则推进了一大步，到达了事物的全体的、本质的、内部联系的东西，到达了暴露周围世界的内在的矛盾，因而能在周围世界的总体上，在周围世界一切方面的内部联系上去把握周围世界的发展。
____

如何深化到理性认知：

____
如果要直接地认识某种或某些事物，便只有亲身参加于变革现实、变革某种或某些事物的实践的斗争中，才能触到那种或那些事物的现象，也只有在亲身参加变革现实的实践的斗争中，才能暴露那种或那些事物的本质而理解它们。
____

=== 实践是真理的标准

值得一题，几十年后另外一位伟人对这句话进行了升华：

____
实践是检验真理的唯一标准
____

有了理性认识还不够，还不满足唯物主义的要求，因为：

____
马克思主义的哲学认为十分重要的问题，不在于懂得了客观世界的规律性，因而能够解释世界，而在于拿了这种对于客观规律性的认识去能动地改造世界。 ....
认识的能动作用，不但表现于从感性的认识到理性的认识之能动的飞跃，更重要的还须表现于从理性的认识到革命的实践这一个飞跃。抓着了世界的规律性的认识，必须把它再回到改造世界的实践中去，再用到生产的实践、革命的阶级斗争和民族斗争的实践以及科学实验的实践中去。
____

也就是说，认知的终极目的还是服务于实践。

=== 认知永远没有完结

认知是没有完结的，一方面认知可能本身存在缺陷，另一方面客观实际是永恒变化的。因此：

____
客观现实世界的变化运动永远没有完结，人们在实践中对于真理的认识也就永远没有完结
____

=== 《实践论》的总结

在党的历史上，错误的实践多次出现，有表现为经验主义的唯心论，还有表现为教条主义的机械唯物论，都对革命造成了重大损失。

大到社会变革，小到个人修为，《实践论》都是具有普适性的。最后，引用领袖在《实践论》的结尾，作为总结：

____
通过实践而发现真理，又通过实践而证实真理和发展真理。从感性认识而能动地发展到理性认识，又从理性认识而能动地指导革命实践，改造主观世界和客观世界。实践、认识、再实践、再认识，这种形式，循环往复以至无穷，而实践和认识之每一循环的内容，都比较地进到了高一级的程度。这就是辩证唯物论的全部认识论，这就是辩证唯物论的知行统一观。
____

== 《矛盾论》

写作背景：

____
这篇哲学论文，是毛泽东继《实践论》之后，为了同一的目的，即为了克服存在于中国共产党内的严重的教条主义思想而写的，曾在延安的抗日军事政治大学作过讲演。在收入本书第一版的时候，作者作了部分的补充、删节和修改。
____

=== 形而上学VS唯物辩证法

形而上学认为：

____
所谓形而上学的或庸俗进化论的宇宙观，就是用孤立的、静止的和片面的观点去看世界。这种宇宙观把世界一切事物，一切事物的形态和种类，都看成是永远彼此孤立和永远不变化的。如果说有变化，也只是数量的增减和场所的变更。而这种增减和变更的原因，不在事物的内部而在事物的外部，即是由于外力的推动。
____

唯物辩证法认为：

____
唯物辩证法的宇宙观主张从事物的内部、从一事物对他事物的关系去研究事物的发展，即把事物的发展看做是事物内部的必然的自己的运动，而每一事物的运动都和它的周围其他事物互相联系着和互相影响着。事物发展的根本原因，不是在事物的外部而是在事物的内部，在于事物内部的矛盾性。
____

用唯物辩证法的观点分析过往的失败：

____
一九二七年中国大资产阶级战败了无产阶级，是通过中国无产阶级内部的（中国共产党内部的）机会主义而起作用的。当着我们清算了这种机会主义的时候，中国革命就重新发展了。后来，中国革命又受了敌人的严重的打击，是因为我们党内产生了冒险主义。当着我们清算了这种冒险主义的时候，我们的事业就又重新发展了。由此看来，一个政党要引导革命到胜利，必须依靠自己政治路线的正确和组织上的巩固。
____

=== 矛盾的普遍性

矛盾的普遍性比较好理解：

____
矛盾的普遍性或绝对性这个问题有两方面的意义。其一是说，矛盾存在于一切事物的发展过程中；其二是说，每一事物的发展过程中存在着自始至终的矛盾运动。
____

=== 矛盾的特殊性

矛盾的特殊性比较有迷惑性，如果认识不深刻，就会滋生教条主义：

____
固然，如果不认识矛盾的普遍性，就无从发现事物运动发展的普遍的原因或普遍的根据；但是，如果不研究矛盾的特殊性，就无从确定一事物不同于他事物的特殊的本质，就无从发现事物运动发展的特殊的原因，或特殊的根据，也就无从辨别事物，无从区分科学研究的领域。 ...
我们的教条主义者在这个问题上的错误，就是，一方面，不懂得必须研究矛盾的特殊性，认识各别事物的特殊的本质，才有可能充分地认识矛盾的普遍性，充分地认识诸种事物的共同的本质；另一方面，不懂得在我们认识了事物的共同的本质以后，还必须继续研究那些尚未深入地研究过的或者新冒出来的具体的事物。
____

认识到矛盾的特殊性非常重要，因为它决定了解决矛盾的方式是战争、革命还是发展生产力：

____
不同质的矛盾，只有用不同质的方法才能解决。例如，无产阶级和资产阶级的矛盾，用社会主义革命的方法去解决；人民大众和封建制度的矛盾，用民主革命的方法去解决；殖民地和帝国主义的矛盾，用民族革命战争的方法去解决；在社会主义社会中工人阶级和农民阶级的矛盾，用农业集体化和农业机械化的方法去解决；共产党内的矛盾，用批评和自我批评的方法去解决；社会和自然的矛盾，用发展生产力的方法去解决。 ...
用不同的方法去解决不同的矛盾，这是马克思列宁主义者必须严格地遵守的一个原则。 ...
我们必须时刻记得列宁的话：对于具体的事物作具体的分析。
____

=== 主要矛盾和矛盾的主要方面

____
在复杂的事物的发展过程中，有许多的矛盾存在，其中必有一种是主要的矛盾，由于它的存在和发展规定或影响着其他矛盾的存在和发展。
____

只有抓住了主要矛盾，才能避免陷入抽象，才能找到正确的解决办法。

=== 同一性和斗争性

所谓同一性，是指矛盾存在对立面，并且彼此依附，在一定条件下可以互相转化（如战场上的攻守）：

____
第一、事物发展过程中的每一种矛盾的两个方面，各以和它对立着的方面为自己存在的前提，双方共处于一个统一体中；第二、矛盾着的双方，依据一定的条件，各向着其相反的方面转化。这些就是所谓同一性。 ...
一切矛盾着的东西，互相联系着，不但在一定条件之下共处于一个统一体中，而且在一定条件之下互相转化，这就是矛盾的同一性的全部意义。
____

同一性是有条件的、暂时的、相对的，但斗争性是无条件的、永恒的、绝对的，因为运动是绝对的：

____
列宁说："`对立的统一（一致、同一、合一），是有条件的、一时的、暂存的、相对的。互相排斥的对立的斗争则是绝对的，正如发展、运动是绝对的一样。`"
____

=== 对抗

____
对抗是矛盾斗争的一种形式，而不是矛盾斗争的一切形式 ...
认识这种情形，极为重要。它使我们懂得，在阶级社会中，革命和革命战争是不可避免的，舍此不能完成社会发展的飞跃，不能推翻反动的统治阶级，而使人民获得政权。共产党人 ...
认识这种情形，极为重要。它使我们懂得，在阶级社会中，革命和革命战争是不可避免的，舍此不能完成社会发展的飞跃，不能推翻反动的统治阶级，而使人民获得政权。共产党人
____

最简单的例子，用战争的方式解决了和帝国主义、资本主义的矛盾，用大力发展生产力解决建国后物质文化需求的矛盾，但在1937年这个历史阶段，有必要把对抗单独拎出来讲。

=== 《矛盾论》的总结

____
事物矛盾的法则，即对立统一的法则，是自然和社会的根本法则，因而也是思维的根本法则。它是和形而上学的宇宙观相反的。它对于人类的认识史是一个大革命。 按照辩证唯物论的观点看来，矛盾存在于一切客观事物和主观思维的过程中，矛盾贯串于一切过程的始终，这是矛盾的普遍性和绝对性。 矛盾着的事物及其每一个侧面各有其特点，这是矛盾的特殊性和相对性。矛盾着的事物依一定的条件有同一性，因此能够共居于一个统一体中，又能够互相转化到相反的方面去，这又是矛盾的特殊性和相对性。然而矛盾的斗争则是不断的，不管在它们共居的时候，或者在它们互相转化的时候，都有斗争的存在，尤其是在它们互相转化的时候，斗争的表现更为显著，这又是矛盾的普遍性和绝对性。当着我们研究矛盾的特殊性和相对性的时候，要注意矛盾和矛盾方面的主要的和非主要的区别；当着我们研究矛盾的普遍性和斗争性的时候，要注意矛盾的各种不同的斗争形式的区别。否则就要犯错误。如果我们经过研究真正懂得了上述这些要点，我们就能够击破违反马克思列宁主义基本原则的不利于我们的革命事业的那些教条主义的思想；也能够使有经验的同志们整理自己的经验，使之带上原则性，而避免重复经验主义的错误。这些，就是我们研究矛盾法则的一些简单的结论。
____

（读懂了《矛盾论》才能读懂这个总结的结构和层次、逻辑和表意）

== 总结

《实践论》和《矛盾论》，在毛选里面属于篇幅中等，但思想上比较晦涩难懂的两篇文章。

以上，是我的一些梳理和感悟。
