---
title: "红利永远都在的"
date: 2020-02-10T20:12:59+08:00
type: post
isCJKLanguage: true
categories:
    - "category1"
tags:
    - "tag1"
    - "tag2"
---

= 红利永远都在的

今天有个同事在群里分享了一件事情，他面试的一个人独立开发了一个**多开app的应用**（一种能让某台手机同时打开多个相同app技术，常见的如微信双开），去年年底已经实现了日入1000~2000的水平，实属让人艳羡。 双开这个东西自己也在用（`VMOS`），因为``同事app``不兼容当前的Android10版本，所以必须通过一个虚拟宿主来启动。市面上还有一个叫``分身大师``的app，是奇虎360做的（因为这个多开技术的起源就是奇虎360的``DroidPlugin``），当我们想去做一个类似产品的时候，就会想，会不会这个市场已经被这两个（可能更多）的专业团队蚕食殆尽了，于是便放弃了。

第二件事情就是在公众号看到一个做自媒体的哥们，年后由于疫情被裁员了，但是这个哥们列举了一些自己的"`副业`"：

* 兼职服务员(KFC，当初干了三年)
* 游戏搬砖，商人
* 写项目
* 公众号
* 芬香与线下教育

他也因为这些副业不至于被突如其来的裁员打垮，其实这些副业和所谓的高大上一点都不沾边，但这哥们通过长期专研，竟然打出一套组合拳，抗住了当前的困难时期。

第三件事是大学QQ群里面看到的，这个寒假，一个校友开发的小程序访问量暴涨，直接突破了100w，这个小程序是用来帮助老师验收作业的，因为这次疫情，大放异彩。

最近看《大国大城》，里面有一个观点：*像中国这种体量的国家，任何一个有价值的垂直领域的创新都会有它的生存空间的*。对于这件事情，我相信技术之外，还要做的是对市场的调研和对产品的增长推广。

很多事情，我不否认其偶然性，但更多的，其实是这些人都有一个特质：爱折腾、有想法。

2019大家觉得公众号到顶了，可还是有人做起来了（我还在坚持写，但并不指望取得什么成就，更多的是锻炼自己的表达）。

*红利永远都在的，很多时候我们觉得红利到头，更多的是我们的格局到头了。*

虽然此刻我是弱小的，虽然成功永远是概率且小概率事件，但还是要坚持去折腾。

不要管别人怎么想，*指挥家都是背对观众的，要想指挥好自己的一生，也要学会背对大环境的噪音*。
