---
title: "为什么读毛选以及怎么读毛选"
date: 2020-10-10T23:41:01+08:00
type: post
isCJKLanguage: true
categories:
    - "读书笔记"
---

= 为什么读毛选以及怎么读毛选

== 为什么读

=== 领袖发家史、中国近代史

首先，《毛选》可以说是领袖的一本自传，也从侧面反映了近代中国从第一次国内革命战争时期到文化大革命时期，70年波澜壮阔的历史。

领袖曾在17岁作诗：

____
《七绝·改诗赠父亲》

孩儿立志出乡关， 学不成名誓不还。  + 埋骨何须桑梓地， 人生无处不青山。
____

在这70年里，领袖从一个普通的无产阶级成长为中国历史上丰碑式的符号；在这70年里，旧中国从半殖民地半封建社会，进入到了文明民主、统一富强的社会主义社会。

比起历史书，《毛选》更加真实，也更加深刻。

=== 学习屠龙之术

《毛选》中最知名的应该是《论持久战》，除此之外，还有多篇类似的文章，其价值和适用的领域已经脱离了具体的时间和空间。

屈原《渔父》有言：

____
圣人不凝滞于物，而能与世推移。
____

《毛选》中有很多宝贵的思想，领袖用它来改造中国，我们也可以活学活用，用它来改造自我。

《毛选》中，名篇如《矛盾论》、《实践论》应该反复研读，这两篇本质上讲的是"`如何认识世界并改造世界`"的问题，也就是如何做到"`知和行`"的统一。

《毛选》中此类佳作甚多，除去方法论，还有很多对时局的分析，比如对抗日战争进程的预测、对蒋发动解放战争的预言等，以至于你有时候会想，日军看了《论持久战》会作何感想。

读《毛选》，不得不感叹领袖经常会先人一步做出预测，即使是马后炮的总结也难如此详实，但本质是领袖已经掌握了这个世界的规律，*所谓"`阳谋`"，不过是"`战略`"对于"`战术`"的降维打击*。

=== 优秀的写作范本

最后，虽说领袖的书法和诗词都汪洋恣肆，非凡人能学习。但是《毛选》里有不少文章，都可以作为日常写作的范本。平时吹的玄之又玄的金字塔原理、三段论等，领袖已经内化成底层能力了。不论是早期的《湖南农民运动考察报告》，还是选入教材的《为人民服务》，都是**结构清晰、言简意赅**的范本。

== 如何读

=== 有的放矢

带着目标去读才不会枯燥无味，才不会陷于教条主义。

=== 立足实际

《毛选》的背景是治国平天下，对于普通人来说过于遥远，但并不妨碍我们活学活用，用来改造我们的工作和生活。譬如其中的"`通过实践检验真理`"、"`具体问题具体分析`"、"`没有调查就没有发言权`"等思想，永远都不会过时。

=== 用发展的眼光读

在不了解领袖经历、中国近代历史的背景下，读《毛选》是很难领会一些言论的特殊历史意义的，毕竟已经脱离了那个特殊的语境。但是，妄图准备好所有的背景知识再去读《毛选》绝对是买椟还珠，所以建议并行阅读，相辅相成地读。

以上，是关于两个问题的思考。

